### ISSUE TITLE
[Feature request] Add Nerd Font icons  depending on the status

### ISSUE THREAD

**Issue by alexxGmZ** [richin13/tmux-plugin-playerctl#2]
It would be nice if there is an icon in the beginning of the text.

![image](https://github.com/user-attachments/assets/c06d131e-8d0c-410e-89bb-962c076eb91e)

I can do this in the `tmux.conf` but it's not dynamic enough.
![image](https://github.com/user-attachments/assets/e851feca-c1bb-493e-891d-bc524f97bab2)
![image](https://github.com/user-attachments/assets/8bac9a8b-1217-454d-a64e-af01feb23f9e)

**Comment by richin13** [comment]
I love the idea, I'll work on it 👍🏼

**Comment by richin13** [comment]
@alexxGmZ thanks for the idea. I've added this functionality in #3. Check out the [README](https://github.com/richin13/tmux-plugin-playerctl?tab=readme-ov-file#settings) to know how to configure it 👍🏼

**Comment by alexxGmZ** [comment]
Nice, thank you

**Comment by crpb** [comment]
btw, you can also just grab the emoji from playerctl
![image](https://github.com/user-attachments/assets/5813fb61-2a61-42ec-b14a-b9110ea3141f)

I also added a few other things to my [fork](https://github.com/richin13/tmux-plugin-playerctl/compare/master...crpb:tmux-plugin-playerctl:master) like volume and a way to ignore e.g. firefox or chromium when something is running in there and `playerctld` somehow thinks this would be the preferred application to show. But because i so extremly changed stuff as this interpolation stuff didn't work out i never opened a pr /ö\\.

![image](https://github.com/user-attachments/assets/384a03d9-d651-4f4a-8483-b2a93b14cf52)
